dist: bionic  # Use a more recent Ubuntu distribution for better stability
language: python
python:
  - "3.10"

# Caching to speed up build times
cache:
  pip: true

# Command to install dependencies with retry logic
install:
  - pip install --retry 5 -r requirements.txt

# Command to run tests and linting
script:
  - pytest
  - flake8 .

# Notifications (optional)
notifications:
  email:
    recipients:
      - ga475@cam.ac.uk
    on_success: never
    on_failure: always
